### ISSUE TITLE
最近没更新了吗

### ISSUE THREAD

**Issue by Shenxiaoy** [d2-projects/d2-daily#132]
日报只到3月22号了。。。

**Comment by FairyEver** [comment]
为期半月的停更通知见微信公众号，掘金沸点，即刻动态

https://juejin.im/pin/5c943a3cf265da6ac2689155

https://m.okjike.com/originalPosts/5c943b360686a00011f8c82c?username=E51AE5A3-8F83-4DA1-9A53-AB5BBFEC78B9

https://mp.weixin.qq.com/s/pnuocx9NOEzMd9ECqdcdNA
