### ISSUE TITLE
分享一个仓库（日报提交助手无法使用，迫于无奈来这里提交）

### ISSUE THREAD

**Issue by azl397985856** [d2-projects/d2-daily#133]
分享一个更加贴近前端的leetcode题解仓库

本仓库目前分为四个部分：

第一个部分是 leetcode 经典题目的解析，包括思路，关键点和具体的代码实现。

第二部分是对于数据结构与算法的总结

第三部分是 anki 卡片， 将 leetcode 题目按照一定的方式记录在 anki 中，方便大家记忆。

第四部分是计划， 这里会记录将来要加入到以上三个部分内容

![image](https://user-images.githubusercontent.com/12479470/55213289-d447ec00-522d-11e9-8c15-accec329d351.png)

项目地址： https://github.com/azl397985856/leetcode

**Comment by FairyEver** [comment]
忘了回复你了，地址呢？

**Comment by azl397985856** [comment]
> 忘了回复你了，地址呢？

忘记了， 已更新
