### ISSUE TITLE
怎么不更新了？

### ISSUE THREAD

**Issue by geek4go** [d2-projects/d2-daily#134]
怎么不更新了？

**Comment by TEsTsLA** [comment]
@geek4go  我也想问，我猜一下。可能发生了经济危机，作者被裁员，心情不好，蹲在家里，打着只狼，还老被boss各式吊打，家里的老妈唧唧哇哇，还有各种房贷要还，一下子愁死了。

**Comment by FairyEver** [comment]
为期半月的停更通知见通知见微信公众号，掘金沸点，即刻动态

https://juejin.im/pin/5c943a3cf265da6ac2689155

https://m.okjike.com/originalPosts/5c943b360686a00011f8c82c?username=E51AE5A3-8F83-4DA1-9A53-AB5BBFEC78B9

https://mp.weixin.qq.com/s/pnuocx9NOEzMd9ECqdcdNA
