### ISSUE TITLE
希望加入 RSS 订阅

### ISSUE THREAD

**Issue by vulgur** [d2-projects/d2-daily#136]
在 即刻 上知道了这个项目，非常感谢整理和分享！
但是网站中没有发现 RSS，希望加入，谢谢！

**Comment by FairyEver** [comment]
RSS [https://github.com/d2-projects/d2-daily/releases.atom](https://github.com/d2-projects/d2-daily/releases.atom)

**Comment by vulgur** [comment]
thx
